### ISSUE TITLE
todo

### ISSUE THREAD

**Issue by dojyorin** [dojyorin/web-crypto#6]
- [x] JS: `clearInputFile()` jsdoc.
- [x] JS: `handleExecDecrypt()` signature verify faild file clear.
- [x] CSS: `header, main` newline.
